// Copyright (c) 2013-2017 Jeffrey Pfau (mGBA), MPL-2.0.
// Ported from mgba/src/sm83/decoder.c and mgba/include/mgba/internal/sm83/decoder.h.
//
// Informational SM83 instruction decoder + disassembler, used by the debugger
// (it does NOT drive execution; the CPU executes via the microcoded handlers
// in `cpu/isa.rs`).
//
// Calling convention, mirroring mGBA's SM83DebuggerTrace
// (mgba/src/sm83/debugger/debugger.c): start from a zeroed
// `SM83InstructionInfo` and feed bytes one at a time; `sm83_decode` returns
// how many *additional* bytes must be fed to complete the instruction:
//
// ```text
// let mut info = SM83InstructionInfo::default();
// let mut bytes_remaining = 1;
// while bytes_remaining > 0 {
//     bytes_remaining += sm83_decode(next_byte(), &mut info);
//     bytes_remaining -= 1;
// }
// let text = sm83_disassemble(&info, address_after_instruction);
// ```
//
// The `pc` argument to `sm83_disassemble` is the address immediately after
// the (fully decoded) instruction, exactly as the C debugger passes it; JR
// targets are rendered relative to it.

use std::fmt::Write;

// ----- enum SM83Condition -----

pub const SM83_COND_NONE: u32 = 0x0;
pub const SM83_COND_C: u32 = 0x1;
pub const SM83_COND_Z: u32 = 0x2;
pub const SM83_COND_NC: u32 = 0x3;
pub const SM83_COND_NZ: u32 = 0x4;

// ----- enum SM83Mnemonic -----

pub const SM83_MN_ILL: u32 = 0;
pub const SM83_MN_ADC: u32 = 1;
pub const SM83_MN_ADD: u32 = 2;
pub const SM83_MN_AND: u32 = 3;
pub const SM83_MN_BIT: u32 = 4;
pub const SM83_MN_CALL: u32 = 5;
pub const SM83_MN_CCF: u32 = 6;
pub const SM83_MN_CP: u32 = 7;
pub const SM83_MN_CPL: u32 = 8;
pub const SM83_MN_DAA: u32 = 9;
pub const SM83_MN_DEC: u32 = 10;
pub const SM83_MN_DI: u32 = 11;
pub const SM83_MN_EI: u32 = 12;
pub const SM83_MN_HALT: u32 = 13;
pub const SM83_MN_INC: u32 = 14;
pub const SM83_MN_JP: u32 = 15;
pub const SM83_MN_JR: u32 = 16;
pub const SM83_MN_LD: u32 = 17;
pub const SM83_MN_LDH: u32 = 18;
pub const SM83_MN_NOP: u32 = 19;
pub const SM83_MN_OR: u32 = 20;
pub const SM83_MN_POP: u32 = 21;
pub const SM83_MN_PUSH: u32 = 22;
pub const SM83_MN_RES: u32 = 23;
pub const SM83_MN_RET: u32 = 24;
pub const SM83_MN_RETI: u32 = 25;
pub const SM83_MN_RL: u32 = 26;
pub const SM83_MN_RLC: u32 = 27;
pub const SM83_MN_RR: u32 = 28;
pub const SM83_MN_RRC: u32 = 29;
pub const SM83_MN_RST: u32 = 30;
pub const SM83_MN_SBC: u32 = 31;
pub const SM83_MN_SCF: u32 = 32;
pub const SM83_MN_SET: u32 = 33;
pub const SM83_MN_SLA: u32 = 34;
pub const SM83_MN_SRA: u32 = 35;
pub const SM83_MN_SRL: u32 = 36;
pub const SM83_MN_STOP: u32 = 37;
pub const SM83_MN_SUB: u32 = 38;
pub const SM83_MN_SWAP: u32 = 39;
pub const SM83_MN_XOR: u32 = 40;
pub const SM83_MN_MAX: u32 = 41;

// ----- enum SM83Register -----

pub const SM83_REG_B: u8 = 1;
pub const SM83_REG_C: u8 = 2;
pub const SM83_REG_D: u8 = 3;
pub const SM83_REG_E: u8 = 4;
pub const SM83_REG_H: u8 = 5;
pub const SM83_REG_L: u8 = 6;
pub const SM83_REG_A: u8 = 7;
pub const SM83_REG_F: u8 = 8;
pub const SM83_REG_BC: u8 = 9;
pub const SM83_REG_DE: u8 = 10;
pub const SM83_REG_HL: u8 = 11;
pub const SM83_REG_AF: u8 = 12;
pub const SM83_REG_SP: u8 = 13;
pub const SM83_REG_PC: u8 = 14;

// ----- SM83_OP_FLAG_* -----

pub const SM83_OP_FLAG_IMPLICIT: u8 = 1;
pub const SM83_OP_FLAG_MEMORY: u8 = 2;
pub const SM83_OP_FLAG_INCREMENT: u8 = 4;
pub const SM83_OP_FLAG_DECREMENT: u8 = 8;
pub const SM83_OP_FLAG_RELATIVE: u8 = 16;

/// struct SM83Operand
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct SM83Operand {
    pub reg: u8,
    pub flags: u8,
    pub immediate: u16,
}

/// struct SM83InstructionInfo
#[derive(Clone, Copy, Debug, Default)]
pub struct SM83InstructionInfo {
    pub opcode: [u8; 3],
    pub opcode_size: usize,
    pub op1: SM83Operand,
    pub op2: SM83Operand,
    pub mnemonic: u32,
    pub condition: u32,
}

// The C decoders are generated per-instruction by the DEFINE_*_SM83 macros and
// dispatched through `_sm83DecoderTable[0x100]` /
// `_sm83CBDecoderTable[0x100]` (built from DECLARE_SM83_EMITTER_BLOCK in
// emitter-sm83.h). Here the two tables are `match` statements in the exact
// order of those blocks; the helpers below play the role of the DEFINE_*
// macro bodies.

/// Maps an SM83 3-bit register encoding (order B, C, D, E, H, L, [HL], A, as
/// generated by DEFINE_*_DECODER_SM83's register lists) to an SM83_REG_* value
/// plus operand flags.
#[inline]
fn reg8(code: u8) -> (u8, u8) {
    match code {
        0 => (SM83_REG_B, 0),
        1 => (SM83_REG_C, 0),
        2 => (SM83_REG_D, 0),
        3 => (SM83_REG_E, 0),
        4 => (SM83_REG_H, 0),
        5 => (SM83_REG_L, 0),
        6 => (SM83_REG_HL, SM83_OP_FLAG_MEMORY),
        7 => (SM83_REG_A, 0),
        _ => unreachable!(),
    }
}

/// DEFINE_DECODER_SM83 default + DEFINE_RST_DECODER_SM83.
#[inline]
fn rst(info: &mut SM83InstructionInfo, vec: u16) -> usize {
    info.mnemonic = SM83_MN_RST;
    info.op1.immediate = vec;
    0
}

/// DEFINE_DECODER_SM83 with a bare mnemonic body (NOP, HALT, ...).
#[inline]
fn mnemonic(info: &mut SM83InstructionInfo, mn: u32) -> usize {
    info.mnemonic = mn;
    0
}

/// DEFINE_LD_DECODER_SM83's immediate form (LD r, d8).
#[inline]
fn ld_r_imm(info: &mut SM83InstructionInfo, reg: u8) -> usize {
    info.mnemonic = SM83_MN_LD;
    info.op1.reg = reg;
    1
}

/// DEFINE_LD_2_DECODER_SM83 (LD rr, d16).
#[inline]
fn ld_rr_imm(info: &mut SM83InstructionInfo, reg: u8) -> usize {
    info.mnemonic = SM83_MN_LD;
    info.op1.reg = reg;
    2
}

/// The 0x40..=0x7F block: DEFINE_LD_DECODER_SM83 for each register
/// (LD r, r' / LD r, [HL] / LD [HL], r). 0x76 (HALT) is excluded by the caller.
#[inline]
fn ld_r_r(opcode: u8, info: &mut SM83InstructionInfo) -> usize {
    let (dst, dst_flags) = reg8((opcode >> 3) & 7);
    let (src, src_flags) = reg8(opcode & 7);
    info.mnemonic = SM83_MN_LD;
    info.op1.reg = dst;
    info.op1.flags = dst_flags;
    info.op2.reg = src;
    info.op2.flags = src_flags;
    0
}

/// The 0x80..=0xBF block: DEFINE_ALU_DECODER_SM83_NOHL/MEM per group of 8
/// (ADD, ADC, SUB, SBC, AND, XOR, OR, CP over B, C, D, E, H, L, [HL], A).
#[inline]
fn alu_r(opcode: u8, info: &mut SM83InstructionInfo) -> usize {
    const ALU_MNEMONICS: [u32; 8] = [
        SM83_MN_ADD, SM83_MN_ADC, SM83_MN_SUB, SM83_MN_SBC, SM83_MN_AND, SM83_MN_XOR, SM83_MN_OR,
        SM83_MN_CP,
    ];
    let (reg, flags) = reg8(opcode & 7);
    info.mnemonic = ALU_MNEMONICS[((opcode >> 3) & 7) as usize];
    info.op1.reg = reg;
    info.op1.flags = flags;
    0
}

/// DEFINE_ALU_DECODER_SM83's immediate form (OP A, d8).
#[inline]
fn alu_imm(info: &mut SM83InstructionInfo, mn: u32) -> usize {
    info.mnemonic = mn;
    info.op1.reg = SM83_REG_A;
    info.op1.flags = SM83_OP_FLAG_IMPLICIT;
    1
}

/// DEFINE_JP_INSTRUCTION_SM83 / DEFINE_CALL_INSTRUCTION_SM83.
#[inline]
fn jp_call(info: &mut SM83InstructionInfo, mn: u32, condition: u32) -> usize {
    info.mnemonic = mn;
    info.condition = condition;
    2
}

/// DEFINE_JR_INSTRUCTION_SM83.
#[inline]
fn jr(info: &mut SM83InstructionInfo, condition: u32) -> usize {
    info.mnemonic = SM83_MN_JR;
    info.condition = condition;
    info.op1.flags = SM83_OP_FLAG_RELATIVE;
    1
}

/// _sm83DecoderTable[opcode], in DECLARE_SM83_EMITTER_BLOCK order.
fn decode_main(opcode: u8, info: &mut SM83InstructionInfo) -> usize {
    match opcode {
        0x00 => mnemonic(info, SM83_MN_NOP), // NOP
        0x01 => ld_rr_imm(info, SM83_REG_BC), // LDBC
        0x02 => {
            // LDBC_A
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_BC;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            0
        }
        0x03 => {
            // INCBC (DEFINE_INCDEC_WIDE_INSTRUCTION_SM83)
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_BC;
            0
        }
        0x04 => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_B;
            0
        }
        0x05 => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_B;
            0
        }
        0x06 => ld_r_imm(info, SM83_REG_B), // LDB_
        0x07 => {
            // RLCA_ (DEFINE_CB_X_DECODER_SM83's accumulator form)
            info.mnemonic = SM83_MN_RLC;
            info.op1.flags = SM83_OP_FLAG_IMPLICIT;
            info.op1.reg = SM83_REG_A;
            0
        }
        0x08 => {
            // LDISP (LD [a16], SP)
            info.mnemonic = SM83_MN_LD;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_SP;
            2
        }
        0x09 => {
            // ADDHL_BC
            info.mnemonic = SM83_MN_ADD;
            info.op1.reg = SM83_REG_HL;
            info.op2.reg = SM83_REG_BC;
            0
        }
        0x0A => {
            // LDA_BC
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_A;
            info.op2.reg = SM83_REG_BC;
            info.op2.flags = SM83_OP_FLAG_MEMORY;
            0
        }
        0x0B => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_BC;
            0
        }
        0x0C => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_C;
            0
        }
        0x0D => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_C;
            0
        }
        0x0E => ld_r_imm(info, SM83_REG_C), // LDC_
        0x0F => {
            // RRCA_
            info.mnemonic = SM83_MN_RRC;
            info.op1.flags = SM83_OP_FLAG_IMPLICIT;
            info.op1.reg = SM83_REG_A;
            0
        }
        0x10 => mnemonic(info, SM83_MN_STOP), // STOP
        0x11 => ld_rr_imm(info, SM83_REG_DE), // LDDE
        0x12 => {
            // LDDE_A
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_DE;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            0
        }
        0x13 => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_DE;
            0
        }
        0x14 => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_D;
            0
        }
        0x15 => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_D;
            0
        }
        0x16 => ld_r_imm(info, SM83_REG_D), // LDD_
        0x17 => {
            // RLA_
            info.mnemonic = SM83_MN_RL;
            info.op1.flags = SM83_OP_FLAG_IMPLICIT;
            info.op1.reg = SM83_REG_A;
            0
        }
        0x18 => jr(info, SM83_COND_NONE), // JR
        0x19 => {
            // ADDHL_DE
            info.mnemonic = SM83_MN_ADD;
            info.op1.reg = SM83_REG_HL;
            info.op2.reg = SM83_REG_DE;
            0
        }
        0x1A => {
            // LDA_DE
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_A;
            info.op2.reg = SM83_REG_DE;
            info.op2.flags = SM83_OP_FLAG_MEMORY;
            0
        }
        0x1B => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_DE;
            0
        }
        0x1C => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_E;
            0
        }
        0x1D => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_E;
            0
        }
        0x1E => ld_r_imm(info, SM83_REG_E), // LDE_
        0x1F => {
            // RRA_
            info.mnemonic = SM83_MN_RR;
            info.op1.flags = SM83_OP_FLAG_IMPLICIT;
            info.op1.reg = SM83_REG_A;
            0
        }
        0x20 => jr(info, SM83_COND_NZ), // JRNZ
        0x21 => ld_rr_imm(info, SM83_REG_HL), // LDHL
        0x22 => {
            // LDIHLA (LD [HL+], A)
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_HL;
            info.op1.flags = SM83_OP_FLAG_INCREMENT | SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            0
        }
        0x23 => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_HL;
            0
        }
        0x24 => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_H;
            0
        }
        0x25 => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_H;
            0
        }
        0x26 => ld_r_imm(info, SM83_REG_H), // LDH_
        0x27 => mnemonic(info, SM83_MN_DAA), // DAA
        0x28 => jr(info, SM83_COND_Z),      // JRZ
        0x29 => {
            // ADDHL_HL
            info.mnemonic = SM83_MN_ADD;
            info.op1.reg = SM83_REG_HL;
            info.op2.reg = SM83_REG_HL;
            0
        }
        0x2A => {
            // LDA_IHL (LD A, [HL+])
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_A;
            info.op2.reg = SM83_REG_HL;
            info.op2.flags = SM83_OP_FLAG_INCREMENT | SM83_OP_FLAG_MEMORY;
            0
        }
        0x2B => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_HL;
            0
        }
        0x2C => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_L;
            0
        }
        0x2D => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_L;
            0
        }
        0x2E => ld_r_imm(info, SM83_REG_L), // LDL_
        0x2F => mnemonic(info, SM83_MN_CPL), // CPL_
        0x30 => jr(info, SM83_COND_NC),     // JRNC
        0x31 => ld_rr_imm(info, SM83_REG_SP), // LDSP
        0x32 => {
            // LDDHLA (LD [HL-], A)
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_HL;
            info.op1.flags = SM83_OP_FLAG_DECREMENT | SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            0
        }
        0x33 => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_SP;
            0
        }
        0x34 => {
            // INC_HL (INC [HL])
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_HL;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            0
        }
        0x35 => {
            // DEC_HL (DEC [HL])
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_HL;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            0
        }
        0x36 => {
            // LDHL_ (LD [HL], d8)
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_HL;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            1
        }
        0x37 => mnemonic(info, SM83_MN_SCF), // SCF
        0x38 => jr(info, SM83_COND_C),       // JRC
        0x39 => {
            // ADDHL_SP
            info.mnemonic = SM83_MN_ADD;
            info.op1.reg = SM83_REG_HL;
            info.op2.reg = SM83_REG_SP;
            0
        }
        0x3A => {
            // LDA_DHL (LD A, [HL-])
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_A;
            info.op2.reg = SM83_REG_HL;
            info.op2.flags = SM83_OP_FLAG_DECREMENT | SM83_OP_FLAG_MEMORY;
            0
        }
        0x3B => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_SP;
            0
        }
        0x3C => {
            info.mnemonic = SM83_MN_INC;
            info.op1.reg = SM83_REG_A;
            0
        }
        0x3D => {
            info.mnemonic = SM83_MN_DEC;
            info.op1.reg = SM83_REG_A;
            0
        }
        0x3E => ld_r_imm(info, SM83_REG_A), // LDA_
        0x3F => mnemonic(info, SM83_MN_CCF), // CCF
        0x76 => mnemonic(info, SM83_MN_HALT), // HALT
        0x40..=0x7F => ld_r_r(opcode, info),
        0x80..=0xBF => alu_r(opcode, info),
        0xC0 => {
            // RETNZ (DEFINE_RET_INSTRUCTION_SM83)
            info.mnemonic = SM83_MN_RET;
            info.condition = SM83_COND_NZ;
            0
        }
        0xC1 => {
            // POPBC (DEFINE_POPPUSH_DECODER_SM83)
            info.mnemonic = SM83_MN_POP;
            info.op1.reg = SM83_REG_BC;
            0
        }
        0xC2 => jp_call(info, SM83_MN_JP, SM83_COND_NZ), // JPNZ
        0xC3 => jp_call(info, SM83_MN_JP, SM83_COND_NONE), // JP
        0xC4 => jp_call(info, SM83_MN_CALL, SM83_COND_NZ), // CALLNZ
        0xC5 => {
            // PUSHBC
            info.mnemonic = SM83_MN_PUSH;
            info.op1.reg = SM83_REG_BC;
            0
        }
        0xC6 => alu_imm(info, SM83_MN_ADD), // ADD
        0xC7 => rst(info, 0x00),            // RST00
        0xC8 => {
            info.mnemonic = SM83_MN_RET;
            info.condition = SM83_COND_Z;
            0
        }
        0xC9 => mnemonic(info, SM83_MN_RET), // RET
        0xCA => jp_call(info, SM83_MN_JP, SM83_COND_Z), // JPZ
        0xCB => 1,                           // CB prefix
        0xCC => jp_call(info, SM83_MN_CALL, SM83_COND_Z), // CALLZ
        0xCD => jp_call(info, SM83_MN_CALL, SM83_COND_NONE), // CALL
        0xCE => alu_imm(info, SM83_MN_ADC), // ADC
        0xCF => rst(info, 0x08),            // RST08
        0xD0 => {
            info.mnemonic = SM83_MN_RET;
            info.condition = SM83_COND_NC;
            0
        }
        0xD1 => {
            info.mnemonic = SM83_MN_POP;
            info.op1.reg = SM83_REG_DE;
            0
        }
        0xD2 => jp_call(info, SM83_MN_JP, SM83_COND_NC), // JPNC
        0xD3 => mnemonic(info, SM83_MN_ILL), // ILL
        0xD4 => jp_call(info, SM83_MN_CALL, SM83_COND_NC), // CALLNC
        0xD5 => {
            info.mnemonic = SM83_MN_PUSH;
            info.op1.reg = SM83_REG_DE;
            0
        }
        0xD6 => alu_imm(info, SM83_MN_SUB), // SUB
        0xD7 => rst(info, 0x10),            // RST10
        0xD8 => {
            info.mnemonic = SM83_MN_RET;
            info.condition = SM83_COND_C;
            0
        }
        0xD9 => mnemonic(info, SM83_MN_RETI), // RETI
        0xDA => jp_call(info, SM83_MN_JP, SM83_COND_C), // JPC
        0xDB => mnemonic(info, SM83_MN_ILL),
        0xDC => jp_call(info, SM83_MN_CALL, SM83_COND_C), // CALLC
        0xDD => mnemonic(info, SM83_MN_ILL),
        0xDE => alu_imm(info, SM83_MN_SBC), // SBC
        0xDF => rst(info, 0x18),            // RST18
        0xE0 => {
            // LDIOA (LDH [a8], A)
            info.mnemonic = SM83_MN_LDH;
            info.op1.immediate = 0xFF00;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            1
        }
        0xE1 => {
            info.mnemonic = SM83_MN_POP;
            info.op1.reg = SM83_REG_HL;
            0
        }
        0xE2 => {
            // LDIOCA (LDH [C], A)
            info.mnemonic = SM83_MN_LDH;
            info.op1.reg = SM83_REG_C;
            info.op1.immediate = 0xFF00;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            0
        }
        0xE3 => mnemonic(info, SM83_MN_ILL),
        0xE4 => mnemonic(info, SM83_MN_ILL),
        0xE5 => {
            info.mnemonic = SM83_MN_PUSH;
            info.op1.reg = SM83_REG_HL;
            0
        }
        0xE6 => alu_imm(info, SM83_MN_AND), // AND
        0xE7 => rst(info, 0x20),            // RST20
        0xE8 => {
            // ADDSP (ADD SP, r8)
            info.mnemonic = SM83_MN_ADD;
            info.op1.reg = SM83_REG_SP;
            1
        }
        0xE9 => {
            // JPHL
            info.mnemonic = SM83_MN_JP;
            info.op1.reg = SM83_REG_HL;
            0
        }
        0xEA => {
            // LDIA (LD [a16], A)
            info.mnemonic = SM83_MN_LD;
            info.op1.flags = SM83_OP_FLAG_MEMORY;
            info.op2.reg = SM83_REG_A;
            2
        }
        0xEB => mnemonic(info, SM83_MN_ILL),
        0xEC => mnemonic(info, SM83_MN_ILL),
        0xED => mnemonic(info, SM83_MN_ILL),
        0xEE => alu_imm(info, SM83_MN_XOR), // XOR
        0xEF => rst(info, 0x28),            // RST28
        0xF0 => {
            // LDAIO (LDH A, [a8])
            info.mnemonic = SM83_MN_LDH;
            info.op1.reg = SM83_REG_A;
            info.op2.immediate = 0xFF00;
            info.op2.flags = SM83_OP_FLAG_MEMORY;
            1
        }
        0xF1 => {
            info.mnemonic = SM83_MN_POP;
            info.op1.reg = SM83_REG_AF;
            0
        }
        0xF2 => {
            // LDAIOC (LDH A, [C])
            info.mnemonic = SM83_MN_LDH;
            info.op1.reg = SM83_REG_A;
            info.op2.reg = SM83_REG_C;
            info.op2.immediate = 0xFF00;
            info.op2.flags = SM83_OP_FLAG_MEMORY;
            0
        }
        0xF3 => mnemonic(info, SM83_MN_DI), // DI
        0xF4 => mnemonic(info, SM83_MN_ILL),
        0xF5 => {
            info.mnemonic = SM83_MN_PUSH;
            info.op1.reg = SM83_REG_AF;
            0
        }
        0xF6 => alu_imm(info, SM83_MN_OR), // OR
        0xF7 => rst(info, 0x30),           // RST30
        0xF8 => {
            // LDHL_SP (LD HL, SP+r8)
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_HL;
            info.op2.reg = SM83_REG_SP;
            1
        }
        0xF9 => {
            // LDSP_HL
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_SP;
            info.op2.reg = SM83_REG_HL;
            0
        }
        0xFA => {
            // LDAI (LD A, [a16])
            info.mnemonic = SM83_MN_LD;
            info.op1.reg = SM83_REG_A;
            info.op2.flags = SM83_OP_FLAG_MEMORY;
            2
        }
        0xFB => mnemonic(info, SM83_MN_EI), // EI
        0xFC => mnemonic(info, SM83_MN_ILL),
        0xFD => mnemonic(info, SM83_MN_ILL),
        0xFE => alu_imm(info, SM83_MN_CP), // CP
        0xFF => rst(info, 0x38),           // RST38
    }
}

/// _sm83CBDecoderTable[opcode], in DECLARE_SM83_CB_EMITTER_BLOCK order. The C
/// generates these from DEFINE_CB_*_DECODER_SM83 macros; the whole space is
/// regular: x = opcode >> 6, y = (opcode >> 3) & 7, z = opcode & 7.
fn decode_cb(opcode: u8, info: &mut SM83InstructionInfo) -> usize {
    let x = opcode >> 6;
    let y = (opcode >> 3) & 7;
    let z = opcode & 7;
    let (reg, flags) = reg8(z);
    match x {
        // DEFINE_CB_1_DECODER_SM83 / DEFINE_CB_X_DECODER_SM83: RLC, RRC, RL,
        // RR, SLA, SRA, SWAP, SRL — operand goes into op1.
        0 => {
            const CB_ROT_MNEMONICS: [u32; 8] = [
                SM83_MN_RLC, SM83_MN_RRC, SM83_MN_RL, SM83_MN_RR, SM83_MN_SLA, SM83_MN_SRA,
                SM83_MN_SWAP, SM83_MN_SRL,
            ];
            info.mnemonic = CB_ROT_MNEMONICS[y as usize];
            info.op1.reg = reg;
            info.op1.flags = flags;
        }
        // DEFINE_CB_DECODER_SM83: BIT/RES/SET y, r — bit index in
        // op1.immediate, operand in op2.
        1..=3 => {
            const CB_BIT_MNEMONICS: [u32; 3] = [SM83_MN_BIT, SM83_MN_RES, SM83_MN_SET];
            info.mnemonic = CB_BIT_MNEMONICS[(x - 1) as usize];
            info.op1.immediate = y as u16;
            info.op2.reg = reg;
            info.op2.flags = flags;
        }
        _ => unreachable!(),
    }
    0
}

/// SM83Decode: feed one byte of an instruction, returns how many additional
/// bytes must be fed (see the calling convention at the top of this file).
pub fn sm83_decode(opcode: u8, info: &mut SM83InstructionInfo) -> usize {
    if info.opcode_size == info.opcode.len() {
        return 0;
    }
    info.opcode[info.opcode_size] = opcode;
    match info.opcode_size {
        0 => {
            info.opcode_size += 1;
            decode_main(opcode, info)
        }
        1 if info.opcode[0] == 0xCB => {
            info.opcode_size += 1;
            decode_cb(opcode, info)
        }
        // Immediate operand bytes: accumulate little-endian into op2 if op1
        // names a register, otherwise into op1.
        _ => {
            info.opcode_size += 1;
            let shift = (info.opcode_size - 2) * 8;
            if info.op1.reg != 0 {
                info.op2.immediate |= (opcode as u16) << shift;
            } else {
                info.op1.immediate |= (opcode as u16) << shift;
            }
            0
        }
    }
}

// ----- Disassembler -----

/// _sm83Conditions (index 0 is NULL in C).
const SM83_CONDITIONS: [Option<&'static str>; 5] =
    [None, Some("c"), Some("z"), Some("nc"), Some("nz")];

/// _sm83Registers
const SM83_REGISTERS: [&'static str; 15] = [
    "", "b", "c", "d", "e", "h", "l", "a", "f", "bc", "de", "hl", "af", "sp", "pc",
];

/// _sm83MnemonicStrings (note: SM83_MN_ILL renders as "--"; the trailing
/// "ill" at index SM83_MN_MAX is never selected by a decoder, same as C).
const SM83_MNEMONIC_STRINGS: [&'static str; (SM83_MN_MAX + 1) as usize] = [
    "--", "adc", "add", "and", "bit", "call", "ccf", "cp", "cpl", "daa", "dec", "di", "ei", "halt",
    "inc", "jp", "jr", "ld", "ldh", "nop", "or", "pop", "push", "res", "ret", "reti", "rl", "rlc",
    "rr", "rrc", "rst", "sbc", "scf", "set", "sla", "sra", "srl", "stop", "sub", "swap", "xor",
    "ill",
];

#[inline]
fn condition_str(condition: u32) -> Option<&'static str> {
    SM83_CONDITIONS.get(condition as usize).copied().flatten()
}

#[inline]
fn register_str(reg: u8) -> &'static str {
    SM83_REGISTERS.get(reg as usize).copied().unwrap_or("")
}

#[inline]
fn mnemonic_str(mnemonic: u32) -> &'static str {
    SM83_MNEMONIC_STRINGS
        .get(mnemonic as usize)
        .copied()
        .unwrap_or("--")
}

/// _decodeOperand: appends the operand's text to `out`; returns whether
/// anything was written (the C returns the character count, which
/// SM83Disassemble only tests for nonzero).
fn decode_operand(out: &mut String, op: &SM83Operand, pc: u16) -> bool {
    if op.flags & SM83_OP_FLAG_IMPLICIT != 0 {
        return false;
    }

    out.push(' ');

    if op.flags & SM83_OP_FLAG_MEMORY != 0 {
        out.push('[');
    }
    if op.reg != 0 {
        let _ = write!(out, "{}", register_str(op.reg));
    } else {
        if op.flags & SM83_OP_FLAG_RELATIVE != 0 {
            // C: snprintf(buffer, blen, "$%04X", pc + (int8_t) op.immediate);
            // evaluated in `int` and printed as unsigned.
            let target = (pc as i32).wrapping_add((op.immediate as u8 as i8) as i32);
            let _ = write!(out, "${:04X}", target as u32);
        } else {
            // C: "$%02X" — minimum width 2, widens for 16-bit immediates.
            let _ = write!(out, "${:02X}", op.immediate);
        }
        // The C has a dead `if (op.reg) "+"` here; op.reg is always 0 in this
        // branch, so it can never fire.
    }
    if op.flags & SM83_OP_FLAG_INCREMENT != 0 {
        out.push('+');
    }
    if op.flags & SM83_OP_FLAG_DECREMENT != 0 {
        out.push('-');
    }
    if op.flags & SM83_OP_FLAG_MEMORY != 0 {
        out.push(']');
    }
    true
}

/// SM83Disassemble: renders `info` as assembly text, byte-for-byte in the
/// C's format. `pc` is the address after the instruction. Unlike the C there
/// is no output buffer to truncate, so the full string is always returned.
pub fn sm83_disassemble(info: &SM83InstructionInfo, pc: u16) -> String {
    let mut out = String::new();
    let mnemonic = mnemonic_str(info.mnemonic);
    let _ = write!(out, "{}", mnemonic);
    // Mirrors the C's `written`, which is only ever tested for nonzero.
    let mut written = !mnemonic.is_empty();

    if let Some(cond) = condition_str(info.condition) {
        let _ = write!(out, " {}", cond);
        written = true;

        if info.op1.reg != 0 || info.op1.immediate != 0 || info.op2.reg != 0 || info.op2.immediate != 0
        {
            out.push(',');
            written = true;
        }
    }

    if info.op1.reg != 0 || info.op1.immediate != 0 || info.op2.reg != 0 || info.op2.immediate != 0 {
        written = decode_operand(&mut out, &info.op1, pc);
    }

    if info.op2.reg != 0
        || (info.op1.immediate == 0 && info.opcode_size > 1 && info.opcode[0] != 0xCB)
    {
        if written {
            out.push(',');
        }
        decode_operand(&mut out, &info.op2, pc);
    }

    out
}

// ----- Instruction length -----

/// _sm83Widths
static SM83_WIDTHS: [u8; 256] = [
    /*      0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F */
    /* 0 */ 1, 3, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 2, 1,
    /* 1 */ 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
    /* 2 */ 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
    /* 3 */ 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
    /* 4 */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* 5 */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* 6 */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* 7 */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* 8 */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* 9 */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* A */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* B */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    /* C */ 1, 1, 3, 3, 3, 1, 2, 1, 1, 1, 3, 2, 3, 3, 2, 1,
    /* D */ 1, 1, 3, 0, 3, 1, 2, 1, 1, 1, 3, 0, 3, 0, 2, 1,
    /* E */ 2, 1, 1, 0, 0, 1, 2, 1, 2, 1, 3, 0, 0, 0, 2, 1,
    /* F */ 2, 1, 1, 1, 0, 1, 2, 1, 2, 1, 3, 1, 0, 0, 2, 1,
];

/// SM83InstructionLength (0 means an illegal opcode).
pub fn sm83_instruction_length(opcode: u8) -> usize {
    SM83_WIDTHS[opcode as usize] as usize
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Feeds `bytes` through `sm83_decode` exactly like mGBA's
    /// SM83DebuggerTrace loop.
    fn decode(bytes: &[u8]) -> SM83InstructionInfo {
        let mut info = SM83InstructionInfo::default();
        let mut bytes_remaining = 1;
        let mut i = 0;
        while bytes_remaining > 0 && i < bytes.len() {
            bytes_remaining += sm83_decode(bytes[i], &mut info);
            i += 1;
            bytes_remaining -= 1;
        }
        info
    }

    #[test]
    fn instruction_length() {
        assert_eq!(sm83_instruction_length(0x00), 1); // NOP
        assert_eq!(sm83_instruction_length(0x01), 3); // LD BC, d16
        // NB: the C _sm83Widths table maps 0xCB to 2, i.e. the *total* width
        // of a CB-prefixed instruction (prefix + sub-opcode).
        assert_eq!(sm83_instruction_length(0xCB), 2);
        assert_eq!(sm83_instruction_length(0x76), 1); // HALT
        assert_eq!(sm83_instruction_length(0x10), 2); // STOP
        assert_eq!(sm83_instruction_length(0xE0), 2); // LDH [a8], A
        assert_eq!(sm83_instruction_length(0xD3), 0); // illegal opcode
    }

    #[test]
    fn decode_cb_prefix() {
        // 0xCB requests one more byte; the follow-up byte is decoded from the
        // CB table.
        let mut info = SM83InstructionInfo::default();
        assert_eq!(sm83_decode(0xCB, &mut info), 1);
        assert_eq!(info.opcode_size, 1);
        assert_eq!(sm83_decode(0x7C, &mut info), 0);
        assert_eq!(info.opcode[0], 0xCB);
        assert_eq!(info.opcode_size, 2);
        assert_eq!(info.mnemonic, SM83_MN_BIT);
        assert_eq!(info.op1.immediate, 7);
        assert_eq!(info.op2.reg, SM83_REG_H);
        assert_eq!(info.op2.flags, 0);
    }

    #[test]
    fn decode_shapes() {
        let info = decode(&[0x00]);
        assert_eq!(info.mnemonic, SM83_MN_NOP);
        assert_eq!(info.opcode_size, 1);

        let info = decode(&[0x01, 0x00, 0x80]); // LD BC, $8000
        assert_eq!(info.mnemonic, SM83_MN_LD);
        assert_eq!(info.op1.reg, SM83_REG_BC);
        assert_eq!(info.op2.immediate, 0x8000);
        assert_eq!(info.opcode_size, 3);

        let info = decode(&[0x22]); // LD [HL+], A
        assert_eq!(info.mnemonic, SM83_MN_LD);
        assert_eq!(
            info.op1.flags,
            SM83_OP_FLAG_INCREMENT | SM83_OP_FLAG_MEMORY
        );

        let info = decode(&[0xC4, 0x56, 0x78]); // CALL NZ, $7856
        assert_eq!(info.mnemonic, SM83_MN_CALL);
        assert_eq!(info.condition, SM83_COND_NZ);
        assert_eq!(info.op1.immediate, 0x7856);

        let info = decode(&[0xD3]); // illegal
        assert_eq!(info.mnemonic, SM83_MN_ILL);
    }

    #[test]
    fn disassemble() {
        // NB on format: _decodeOperand emits a leading space before every
        // operand, so the C renders "ld a, $05" / "bit $07, h" (space after
        // the separating comma). These strings are the exact mGBA output.
        assert_eq!(sm83_disassemble(&decode(&[0x00]), 0), "nop");
        assert_eq!(sm83_disassemble(&decode(&[0x3E, 0x05]), 0), "ld a, $05");
        assert_eq!(sm83_disassemble(&decode(&[0x01, 0x34, 0x12]), 0), "ld bc, $1234");
        assert_eq!(sm83_disassemble(&decode(&[0xC3, 0x34, 0x12]), 0), "jp $1234");
        assert_eq!(sm83_disassemble(&decode(&[0xCD, 0x56, 0x78]), 0), "call $7856");
        assert_eq!(
            sm83_disassemble(&decode(&[0xC4, 0x56, 0x78]), 0),
            "call nz, $7856"
        );
        // JR targets are relative to the address after the instruction.
        assert_eq!(sm83_disassemble(&decode(&[0x18, 0xFE]), 0x0102), "jr $0100");
        assert_eq!(
            sm83_disassemble(&decode(&[0x20, 0xFE]), 0x0102),
            "jr nz, $0100"
        );
        assert_eq!(sm83_disassemble(&decode(&[0xCB, 0x7C]), 0), "bit $07, h");
        assert_eq!(sm83_disassemble(&decode(&[0xCB, 0x37]), 0), "swap a");
        assert_eq!(sm83_disassemble(&decode(&[0x22]), 0), "ld [hl+], a");
        assert_eq!(sm83_disassemble(&decode(&[0x34]), 0), "inc [hl]");
        assert_eq!(sm83_disassemble(&decode(&[0xF0, 0x42]), 0), "ldh a, [$FF42]");
        assert_eq!(sm83_disassemble(&decode(&[0xF5]), 0), "push af");
        assert_eq!(sm83_disassemble(&decode(&[0xFF]), 0), "rst $38");
        assert_eq!(sm83_disassemble(&decode(&[0x07]), 0), "rlc");
        // ALU immediate: the implicit "a" operand prints nothing, so there is
        // no comma — exactly like the C (its `written` stays 0).
        assert_eq!(sm83_disassemble(&decode(&[0xC6, 0x12]), 0), "add $12");
        assert_eq!(sm83_disassemble(&decode(&[0xD3]), 0), "--");
    }
}
